export const react = require("./react.png");
export const js = require("./js (1).png");
export const python = require("./python.png");
export const clanguage = require("./letter-c.png")
export const html = require("./html-5.png");
export const css = require("./css-3.png");
export const tailwind  = require("./Tailwind.png");
export const material = require("./material.png");
export const jquery =  require("./pngegg.png");
export const mysql = require("./mysql.png");
export const mongo = require("./mongo.png");
export const express = require("./expressjs.png");
export const flask = require("./flask.png");
export const git = require("./git.jpg");